language: generic 
services:
    - docker
    
before_install:
    - docker build -t ordaniel/docker-react-travis-internal -f Dockerfile.dev .

script:
    - docker run -e CI=true ordaniel/docker-react-travis-internal npm run test